package upload_service

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"path/filepath"
	"regexp"
	"slices"

	core_domain "github.com/PopovMarko/tailverse-petnet/internal/core/domain"
	core_errors "github.com/PopovMarko/tailverse-petnet/internal/core/errors"
)

// MaxUploadSize is the largest accepted file, 10 MB.
const MaxUploadSize = 10 << 20

// extensions maps every accepted image type to the extension of the stored file.
var extensions = map[string]string{
	"image/jpeg": ".jpg",
	"image/png":  ".png",
	"image/webp": ".webp",
	"image/heic": ".heic",
}

// contentTypes is used when a stored file is served back.
var contentTypes = map[string]string{
	".jpg":  "image/jpeg",
	".png":  "image/png",
	".webp": "image/webp",
	".heic": "image/heic",
}

// fileNamePattern matches the names generated by newFileName; anything else is never looked up on disk.
var fileNamePattern = regexp.MustCompile(`^[0-9a-f]{32}\.(jpg|png|webp|heic)$`)

// heicBrands are the ISO-BMFF brands used by HEIC/HEIF images from phone cameras.
var heicBrands = []string{"heic", "heix", "hevc", "hevx", "heim", "heis", "hevm", "hevs", "mif1", "msf1"}

type FileRepository interface {
	Save(ctx context.Context, name string, content []byte) error
	Open(ctx context.Context, name string) (core_domain.StoredFile, error)
}

type UploadService struct {
	repository  FileRepository
	newFileName func() (string, error)
}

func NewUploadService(repository FileRepository) *UploadService {
	return &UploadService{
		repository:  repository,
		newFileName: randomFileName,
	}
}

// Upload validates and stores an image. The type is detected from the file content, not from what the client declares.
func (s *UploadService) Upload(ctx context.Context, content io.Reader) (core_domain.Upload, error) {
	data, err := io.ReadAll(io.LimitReader(content, MaxUploadSize+1))
	if err != nil {
		return core_domain.Upload{}, fmt.Errorf("read file: %w", err)
	}
	if len(data) == 0 {
		return core_domain.Upload{}, fmt.Errorf("file is empty: %w", core_errors.ErrInvalidArgument)
	}
	if len(data) > MaxUploadSize {
		return core_domain.Upload{}, fmt.Errorf("file is larger than %d MB: %w", MaxUploadSize>>20, core_errors.ErrTooLarge)
	}

	contentType, ok := DetectImageType(data)
	if !ok {
		return core_domain.Upload{}, fmt.Errorf("only JPEG, PNG, WebP and HEIC images are accepted: %w", core_errors.ErrUnsupportedMediaType)
	}

	baseName, err := s.newFileName()
	if err != nil {
		return core_domain.Upload{}, fmt.Errorf("generate file name: %w", err)
	}
	name := baseName + extensions[contentType]

	if err := s.repository.Save(ctx, name, data); err != nil {
		return core_domain.Upload{}, fmt.Errorf("save file: %w", err)
	}
	return core_domain.Upload{Name: name, ContentType: contentType, Size: int64(len(data))}, nil
}

// Open returns a stored file. Names that the service could not have generated are reported as not found.
func (s *UploadService) Open(ctx context.Context, name string) (core_domain.StoredFile, error) {
	if !fileNamePattern.MatchString(name) {
		return core_domain.StoredFile{}, fmt.Errorf("no upload named %q: %w", name, core_errors.ErrNotFound)
	}
	file, err := s.repository.Open(ctx, name)
	if err != nil {
		return core_domain.StoredFile{}, fmt.Errorf("open file: %w", err)
	}
	file.ContentType = contentTypes[filepath.Ext(name)]
	return file, nil
}

// DetectImageType recognises the accepted image formats by their magic bytes.
func DetectImageType(data []byte) (string, bool) {
	switch {
	case bytes.HasPrefix(data, []byte{0xFF, 0xD8, 0xFF}):
		return "image/jpeg", true
	case bytes.HasPrefix(data, []byte("\x89PNG\r\n\x1a\n")):
		return "image/png", true
	case len(data) >= 12 && bytes.Equal(data[0:4], []byte("RIFF")) && bytes.Equal(data[8:12], []byte("WEBP")):
		return "image/webp", true
	case len(data) >= 12 && bytes.Equal(data[4:8], []byte("ftyp")) && slices.Contains(heicBrands, string(data[8:12])):
		return "image/heic", true
	default:
		return "", false
	}
}

func randomFileName() (string, error) {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}
